/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author angel
 */
public class FormCrearCuenta extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormCrearCuenta.class.getName());

    /**
     * Creates new form FormCrearCuenta
     */
    public FormCrearCuenta() {
        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblCR = new javax.swing.JLabel();
        lblnombreE1 = new javax.swing.JLabel();
        lblSlogan1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        lblLogin = new javax.swing.JLabel();
        lblIniciar = new javax.swing.JLabel();
        lblContra = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        btnCrear = new javax.swing.JButton();
        lblUsuario = new javax.swing.JLabel();
        lblnoC1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1920, 1080));

        jPanel1.setBackground(new java.awt.Color(0, 56, 78));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/apolo - Editado.png"))); // NOI18N
        jPanel3.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        lblCR.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCR.setForeground(new java.awt.Color(0, 56, 78));
        lblCR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCR.setText("copyright ©️ Centro Apolo All rights reserved");
        jPanel3.add(lblCR, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 520, -1));

        lblnombreE1.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        lblnombreE1.setForeground(new java.awt.Color(0, 56, 78));
        lblnombreE1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblnombreE1.setText("CENTRO INFORMÁTICO");
        jPanel3.add(lblnombreE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 530, -1));

        lblSlogan1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSlogan1.setForeground(new java.awt.Color(0, 56, 78));
        lblSlogan1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSlogan1.setText("Tu aliado en innovación tecnológica");
        jPanel3.add(lblSlogan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 530, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 660));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setForeground(new java.awt.Color(0, 56, 78));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 290, 10));

        lblLogin.setBackground(new java.awt.Color(48, 54, 79));
        lblLogin.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(0, 56, 78));
        lblLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogin.setText("CREAR CUENTA");
        jPanel2.add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 15, 490, -1));

        lblIniciar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblIniciar.setForeground(new java.awt.Color(255, 0, 0));
        lblIniciar.setText("Inicia Sesión Aquí");
        lblIniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblIniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIniciarMouseClicked(evt);
            }
        });
        jPanel2.add(lblIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 530, -1, -1));

        lblContra.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblContra.setForeground(new java.awt.Color(0, 56, 78));
        lblContra.setText("Contraseña");
        jPanel2.add(lblContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        txtUsuario.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jPanel2.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 380, 40));

        txtPass.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jPanel2.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 380, 40));

        btnCrear.setBackground(new java.awt.Color(0, 56, 78));
        btnCrear.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnCrear.setForeground(new java.awt.Color(255, 255, 255));
        btnCrear.setText(" Crear Cuenta");
        btnCrear.addActionListener(this::btnCrearActionPerformed);
        jPanel2.add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 140, 40));

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(0, 56, 78));
        lblUsuario.setText("Usuario");
        jPanel2.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        lblnoC1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblnoC1.setForeground(new java.awt.Color(0, 56, 78));
        lblnoC1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblnoC1.setText("Ya tengo cuenta");
        jPanel2.add(lblnoC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 530, -1, -1));

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 380, 40));

        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(0, 56, 78));
        lblNombre.setText("Nombre");
        jPanel2.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, -1, 560));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearActionPerformed

    private void lblIniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIniciarMouseClicked
        // TODO add your handling code here:
        FormLogin login = new FormLogin();
        login.setVisible(true);
        login.pack();
        login.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_lblIniciarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormCrearCuenta().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCR;
    private javax.swing.JLabel lblContra;
    private javax.swing.JLabel lblIniciar;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblSlogan1;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblnoC1;
    private javax.swing.JLabel lblnombreE1;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
